Run black.
uktrade/trade-remedies-caseworker pull request #10
Opened 2020-10-15 15:19 UTC by Luisella21

2020-10-28 14:14 UTC, Luisella21 commented
Applied  black to the code base, run flake8 and fixed the relevant errors. Changed circleci configuration to run black and flake8.

2020-10-29 12:39 UTC, rossmiller requested changes
Looks good! A few items to check.

2020-11-12 08:52 UTC, Luisella21 commented on trade_remedies_caseworker/.flake8
> +# application-import-names = cases,contacts,core,documents,govuk_template,manage.py,tasks,templates,trade_remedies_caseworker, users
No real reason. It is irrelevant because we don't use flake8-import-order. I un-commented it.

2020-11-12 09:29 UTC, Luisella21 commented on trade_remedies_caseworker/core/auth.py
> +        # TODO Fix undefind 'email'
The TODO is redundant. I created a new ticket to address the flake error for undefined variables. 
Removed.

2020-11-12 09:30 UTC, Luisella21 commented on trade_remedies_caseworker/cases/views.py
> +                        # TODO Fix undefined 'submission_id'.
The TODO is redundant. I created a new ticket to address the flake error for undefined variables. 
Removed.

2020-11-12 09:31 UTC, Luisella21 commented on trade_remedies_caseworker/core/models.py
> +        # TODO fixed undefined 'get_user'
Removed.

2020-11-24 12:09 UTC, rossmiller approved these changes

2020-11-24 12:09 UTC, merged