TRSV2-144: editable inform interested parties preview
uktrade/trade-remedies-caseworker pull request #126
Opened 2022-03-25 09:46 UTC by KnowYourLines

2022-03-25 13:10 UTC, nboyse requested changes
Looks good just need to amend the gitignore

2022-03-25 13:32 UTC, KnowYourLines commented on .gitignore
> +fitness/fitness_metrics_graph.png
Temporary fix to prevent merge conflicts for now until @chris-pettinga figures out what we really want. Think it's beyond the scope of this ticket to sort out in this PR.

2022-03-25 13:38 UTC, KnowYourLines commented on .gitignore
> +fitness/fitness_metrics_graph.png
Gonna merge develop into branch and resolve the conflicts manually until it's sorted, i.e. accept develop's fitness database since it seems they need to be in VCS

2022-03-28 08:40 UTC, nboyse approved these changes

2022-03-28 08:41 UTC, merged

2022-03-28 11:59 UTC, chris-pettinga commented on trade_remedies_caseworker/organisations/views.py
> +def invite_template_change(request):
Can you make this a class-based view like the others in this file

2022-03-28 11:59 UTC, chris-pettinga commented on trade_remedies_caseworker/organisations/views.py
> +        _client = TradeRemediesAPIClientMixin.client(request, request.user)
If class view, we can inherit from the Mixin and just call self.client()

2022-03-28 11:59 UTC, chris-pettinga commented on trade_remedies_caseworker/templates/cases/invite.html
> +                alert(result)
Do we need this?

2022-03-28 11:59 UTC, chris-pettinga commented on trade_remedies_caseworker/templates/cases/invite.html
> +        const csrf_token = object.parentElement.parentElement[0].value
Replace with:

`$('[name=csrfmiddlewaretoken]').val();`

2022-03-28 11:59 UTC, chris-pettinga commented on trade_remedies_caseworker/templates/cases/invite.html
> +        const submitButton = jQuery('#sendButton');
no need to use jQuery if we're not going to use the jQuery object:

`document.getElementById('sendButton')`