V2Feature - TRSV2-203 : Login Journey
uktrade/trade-remedies-caseworker pull request #152
Opened 2022-05-17 15:25 UTC by chris-pettinga

2022-05-25 09:30 UTC, KnowYourLines requested changes

2022-05-25 09:30 UTC, KnowYourLines commented on requirements/base.txt
> +trade-remedies-client @ git+https://github.com/uktrade/trade-remedies-client.git@v2feature/trsv2-174/login-journey
This probably needs updating

2022-05-25 09:30 UTC, KnowYourLines commented on requirements/dev.txt
> +trade-remedies-client @ git+https://github.com/uktrade/trade-remedies-client.git@v2feature/trsv2-174/login-journey
Same as above

2022-05-25 09:30 UTC, KnowYourLines commented on requirements/prod.txt
> +trade-remedies-client @ git+https://github.com/uktrade/trade-remedies-client.git@v2feature/trsv2-174/login-journey
Likewise

2022-05-25 09:30 UTC, KnowYourLines commented on requirements.in/base.in
> +git+https://github.com/uktrade/trade-remedies-client.git@v2feature/trsv2-174/login-journey#trade-remedies-client
Should update this before merging

2022-05-25 09:30 UTC, KnowYourLines commented
LGTM client library requirement just needs updating

2022-06-07 09:14 UTC, chris-pettinga commented on requirements/base.txt
> +trade-remedies-client @ git+https://github.com/uktrade/trade-remedies-client.git@v2feature/trsv2-174/login-journey
Same comment for the below

2022-06-07 09:28 UTC, KnowYourLines approved these changes

2022-06-07 09:30 UTC, KnowYourLines commented
Leaving this pointing to the https://github.com/uktrade/trade-remedies-client/pull/12 unmerged until this is tested in UAT and ready for prod release as merging https://github.com/uktrade/trade-remedies-client/pull/12 would break current production journeys

2022-06-07 10:20 UTC, merged