TRLST-169 branding changes
uktrade/trade-remedies-caseworker pull request #16
Opened 2020-11-18 14:11 UTC by jwgulley

These are changes for making updates to the branding as described in TRLST-169.  Tipu has kindly reviewed the result and declared himself happy with it..  This PR is for review only at this stage, but with a view to it being approved and applied when the branding update is required.

Please review, specifically examining the changes to the fixtures, as it is not clear whether these are needed.

Known Issues

These changes do not include:
- updates to any documents - e.g. letter of authority templates or email templates;
- updates to the database - see the ticket comment for details, also the fixture changes may be relevant.

2020-11-18 15:40 UTC, markhigham approved these changes
LGTM

2020-11-18 17:26 UTC, davecharles reviewed
Looks fine but could we use a combination of custom template tags (for the HTML) and calls to `get_system_parameters` (e.g. `Client().get_system_parameters('APP_BRAND')`? This means we can affect the change more easily at the correct time with a quick change in the apis `system/parameters.json`.

2020-11-19 09:29 UTC, rossmiller requested changes
Could we make the name of the product and its initialism a settings variable tied to an env var? That way we can change it any time.

2020-11-19 09:46 UTC, jwgulley commented
I think this needs to be discussed.  The change will happen over the Christmas break, so my call was to keep it as simple as possible to avoid disrupting people's seasonal break.  Also, I think org name changes are actually likely to be rather rare.  Finally, the testing / reviewing work here is probably as substantial than the actual development.

It is worth noting that there are some file names referring to TRID - some might argue that a second set of changes will be needed in order to change those filenames and it would be better to do any automation at that point - i.e not during the holiday season.

2020-11-19 09:57 UTC, davecharles commented
The intention is to minimise the change at that time (xmas) by parameterising it now, but using values for current branding (TRID etc). Then at EOY it's a simple var change that's low ceremony/low risk. My experience is that branding changes regularly enough (don't get me started 😆 ) to make this worth the effort now tbh.

2020-11-19 09:59 UTC, jwgulley commented
Actually. there's more to say here.  If you are going to go down the route suggested, there is also a case for making a string table containing every string in the system.  The reason for doing this would be to support localisation - i.e. so that the web-site can implemented in different languages.

2020-11-19 10:51 UTC, rossmiller commented
Sorry, I hadn't read @davecharles  comment re system params. I think either this approach or using a Django setting is fine. Both will need a template tag - https://docs.djangoproject.com/en/3.1/howto/custom-template-tags/

Please call the variables ORGANISATION_NAME and ORGANISATION_INITIALISM

2020-11-20 15:08 UTC, davecharles requested changes
I think we can remove the old `TRID_full_name.html` and `TRID_abbreviation.html` files

2020-11-20 15:08 UTC, davecharles commented on trade_remedies_caseworker/templates/TRID_abbreviation.html
> +TRA
This file is not used anymore

2020-11-20 15:08 UTC, davecharles commented on trade_remedies_caseworker/templates/TRID_full_name.html
> +Trade Remedies Authority
This file is not used anymore

2020-11-20 15:20 UTC, jwgulley commented
> 
> 
> Could we make the name of the product and its initialism a settings variable tied to an env var? That way we can change it any time.
These are now set in local.env, at least for dev purposes - was that what you meant?

2020-11-24 11:30 UTC, rossmiller approved these changes
LGTM!

2020-11-25 09:59 UTC, davecharles approved these changes
LGTM

2020-11-26 11:17 UTC, rossmiller requested changes
Could you add the new env vars to local.env.example and an entry in the readme to explain them please?

2020-11-26 11:19 UTC, rossmiller requested changes

2020-11-26 11:19 UTC, rossmiller commented on trade_remedies_caseworker/core/templatetags/organisation_initialism.py
> +Template tag to display organisation name and organisation initialism
Please change text to "Template tag to display organisation initialism"

2020-11-26 11:53 UTC, jwgulley commented on trade_remedies_caseworker/core/templatetags/organisation_initialism.py
> +Template tag to display organisation name and organisation initialism
Thank-you - updated.

2020-11-26 13:54 UTC, rossmiller approved these changes
LGTM!

2020-11-26 13:54 UTC, merged