TRLST-153 candidate fix
uktrade/trade-remedies-caseworker pull request #19
Opened 2020-11-23 15:42 UTC by jwgulley

Another Javascript-based fix, this time based on boilerplate code from w3schools.

2020-11-25 11:09 UTC, rossmiller requested changes
Minor update required.

2020-11-25 11:09 UTC, rossmiller commented on trade_remedies_caseworker/templates/organisations/organisations.html
> +    console.log( filter );
Can we remove the console.log please?

2020-11-26 14:27 UTC, jwgulley commented on trade_remedies_caseworker/templates/organisations/organisations.html
> +    console.log( filter );
Thanks - good spot.  Updated further to comment.

2020-12-01 10:31 UTC, rossmiller approved these changes
LGTM!

2020-12-01 10:32 UTC, merged