Feature/trlst 173 caseworker 3pi journey
uktrade/trade-remedies-caseworker pull request #24
Opened 2020-12-17 16:08 UTC by davecharles

# Implement [TRLST-173](https://uktrade.atlassian.net/browse/TRLST-173?atlOrigin=eyJpIjoiYmNiYmQxOGExN2FhNGZiNTgwYmFlNDYzNWFmY2ZiNjkiLCJwIjoiaiJ9)
This PR implements Casework Portal 3rd Party Invite journey (excluding the invite decline/deficient journey).

# Summary
The codebase is challenging and has monolithic view modules and associated view classes. In addition the templates contain too much logic. In lieu of some serious refactoring have added these changes to intrude as little as possible so the changes are clear. They mainly comprise a few fixes, template updates to accommodate the rendering of 3P invites (submissions) and view code changes, so in general:
1. Fix `save and continue` button behaviour on the "submissions"/submission review page.
1. Display 3P invitee panels for a given case and organisation on the "parties" page .

Specifically:
- In `SubmissionView` identified 3P submission as such to drive template rendering.
- In `SubmissionView.post`, refetch submission data for the case. This wasn't working and affecting the "save+continue" functionality. This is because the API get_submission endpoint is not implemented properly. Have added TODO comments accordingly.
- Further on in this monster 200 line post method that handles all post routes (face with rolling eyes) added call to new  `update_submission_status` method that updates the submission document statuses with a call to the API, on submission approval.
- Updated `OrganisationDetailsView` to support display of third party contacts. Added code to establish 3P invitees wrt the originating organisation so they can be displayed in the right org panel. Added method to build third party contact list from this.

2020-12-17 16:26 UTC, rossmiller requested changes
Looks good! A couple of comments to address.

2020-12-17 16:26 UTC, rossmiller commented on .gitignore
> +db.sqlite3
I think you should use assume unchanged rather than ignore. The DB should be in the repo but not updated by commits.

2020-12-17 16:26 UTC, rossmiller commented on trade_remedies_caseworker/cases/views.py
> +                # TODO: API client `update_submission` call routes to
Are these to implemented going forward?

2020-12-18 09:37 UTC, davecharles commented on trade_remedies_caseworker/cases/views.py
> +                # TODO: API client `update_submission` call routes to
Good question - this was only affecting my use case because the updating the returned response to the `self._client.update_submission`call was incomplete (empty documents list). I needed the documents in the new `update_submission_status` method. I think this should be picked up in (1) refactor of API (2) refactoring these _massive_ views/methods.

2020-12-18 09:39 UTC, davecharles commented on .gitignore
> +db.sqlite3
Fair enough, I have misunderstood the role of the SQLite DB, I looked at the content, it had a schema but no data I thought was relevant.

2020-12-18 15:40 UTC, davecharles commented on .gitignore
> +db.sqlite3
Resolved with b5a5e00

2020-12-18 15:41 UTC, davecharles commented on trade_remedies_caseworker/cases/views.py
> +                # TODO: API client `update_submission` call routes to
Resolved with 0177afa and created [TRLST-217](https://uktrade.atlassian.net/browse/TRLST-217)

2020-12-21 09:54 UTC, rossmiller approved these changes
LGTM!

2020-12-21 10:08 UTC, merged