TRSLT-10: show published status in Submissions view
uktrade/trade-remedies-caseworker pull request #7
Opened 2020-10-09 11:36 UTC by jwgulley

get more info re each submission from TR-API and use it to indicate Published status in Submissions view

2020-10-09 16:54 UTC, rossmiller requested changes
Please take a look at my comments.

2020-10-09 16:54 UTC, rossmiller commented on trade_remedies_caseworker/templates/cases/submissions.html
> +                                    {% if submission.issued_at %}<span style="color:green; float:right">Published</span>{% endif %}
Can we do the styling in a spreadsheet rather than inline?

2020-10-09 16:54 UTC, rossmiller commented on trade_remedies_caseworker/cases/views.py
> +            self.case_id, show_global=True
Does this need a unit test?

2020-10-09 17:11 UTC, jwgulley commented on trade_remedies_caseworker/cases/views.py
> +            self.case_id, show_global=True
Thanks for your suggestion.  The fix is to the way the program looks.  I'm happy to do a unit test but I don't know how to set it up and actually no idea of what one would usefully test - it's just sending another parameter (as used in Submission) to the client api.  The main thing is to have plenty of other unit tests of key stuff and ensure this minor change does not break them.

2020-10-09 17:11 UTC, jwgulley commented on trade_remedies_caseworker/templates/cases/submissions.html
> +                                    {% if submission.issued_at %}<span style="color:green; float:right">Published</span>{% endif %}
Great question.  Yes, I tried to do that, but something unknown is fixing the number of columns!!!  Hence the pragmatic choice I made to follow the style of the existing code and keep it inline.  
Also, if we were to succeed in changing the number of columns one might want to do it in respect of lines 97, 98, 99, which might introduce more extensive issues of layout.  Tipu has had a preview and seemed happy enough.

2020-10-12 12:59 UTC, markhigham approved these changes
ok subject to unit testing

2020-10-14 13:58 UTC, rossmiller approved these changes
Looks good! This MUST have a manual smoke test of the affected view.

2020-10-14 15:04 UTC, merged

2020-10-14 16:23 UTC, jwgulley commented
Thank-you, Ross, Mark and Tipu, for your kind help and support.