updated sortval to remove span tag & removed spurious </td>
uktrade/trade-remedies-caseworker pull request #8
Opened 2020-10-12 08:52 UTC by jwgulley

I have tested this fix on:
https://trade-remedies-caseworker-dev.london.cloudapps.digital/case/3fede0bb-6c8c-4fb4-889f-7da6435ae39a/files/

2020-10-20 09:01 UTC, markhigham requested changes

2020-10-20 09:01 UTC, markhigham commented on trade_remedies_caseworker/templates/cases/files.html
> +        <td class="nobreak" sortVal="{{document.created_at}}">
Shouldn't this be `{{ document.created_at|format_date:'%Y%m%d'}}`

2020-10-21 08:57 UTC, markhigham requested changes

2020-10-21 08:57 UTC, markhigham commented on trade_remedies_caseworker/templates/cases/files.html
> +        <td class="nobreak" sortVal={{ document.created_at|format_date_no_span:'%Y_%m_%d'}}  >
I checked this. Not sure why the built in date doesn't work!! But this is a good solution.
You just need to surround the {{ with some quotes

`sortVal="{{ document.created_at|format_date_no_span:'%Y_%m_%d'}}"`

2020-10-22 08:51 UTC, jwgulley commented on trade_remedies_caseworker/templates/cases/files.html
> +        <td class="nobreak" sortVal={{ document.created_at|format_date_no_span:'%Y_%m_%d'}}  >
Thanks for your kind feedback, Mark.  I've now added the quote marks, tested it and updated the PR.

2020-10-22 09:57 UTC, markhigham approved these changes
:octocat: TMLG

2020-10-22 11:12 UTC, merged